name: 'Clone Repositories'
description: 'Clone self and upstream repositories'

inputs:
  ecosystem-ci-project:
    description: 'The ecosystem ci project to clone'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Output ecosystem ci project hash
      shell: bash
      id: ecosystem-ci-project-hash
      if: ${{ inputs.ecosystem-ci-project != '' }}
      run: |
        node -e "console.log('ECOSYSTEM_CI_PROJECT_HASH=' + require('./ecosystem-ci/repo.json')['${{ inputs.ecosystem-ci-project }}'].hash)" >> $GITHUB_OUTPUT
        node -e "console.log('ECOSYSTEM_CI_PROJECT_REPOSITORY=' + require('./ecosystem-ci/repo.json')['${{ inputs.ecosystem-ci-project }}'].repository.replace('https://github.com/', '').replace('.git', ''))" >> $GITHUB_OUTPUT

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      if: ${{ inputs.ecosystem-ci-project != '' }}
      with:
        repository: ${{ steps.ecosystem-ci-project-hash.outputs.ECOSYSTEM_CI_PROJECT_REPOSITORY }}
        path: ecosystem-ci/${{ inputs.ecosystem-ci-project }}
        ref: ${{ steps.ecosystem-ci-project-hash.outputs.ECOSYSTEM_CI_PROJECT_HASH }}
