packages:
  - packages/*
  - plugins/*
  - examples/*
  - tools/*
  - site

catalog:
  '@clack/prompts': ^0.11.0
  '@eggjs/compressible': ^3.0.0
  '@eggjs/i18n': ^3.0.1
  '@eggjs/logrotator': ^4.0.0
  '@eggjs/multipart': ^4.0.0
  '@eggjs/router': ^3.0.5
  '@eggjs/security': ^4.0.0
  '@eggjs/session': ^4.0.1
  '@eggjs/tegg': ^3.2.2
  '@eggjs/tegg-config': ^3.2.2
  '@eggjs/tegg-controller-plugin': ^3.2.2
  '@eggjs/tegg-plugin': ^3.2.2
  '@eggjs/view': ^3.0.1
  '@fengmk2/ps-tree': ^2.0.1
  '@oclif/core': ^4.2.0
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.13.5
  '@types/accepts': ^1.3.7
  '@types/body-parser': ^1.19.5
  '@types/content-disposition': ^0.5.8
  '@types/content-type': ^1.1.8
  '@types/cookie-parser': ^1.4.8
  '@types/cookies': ^0.9.0
  '@types/cross-spawn': ^6.0.6
  '@types/destroy': ^1.0.3
  '@types/encodeurl': ^1.0.2
  '@types/escape-html': ^1.0.4
  '@types/express': ^5.0.0
  '@types/fresh': ^0.5.2
  '@types/fs-readdir-recursive': ^1.1.3
  '@types/http-errors': ^2.0.4
  '@types/js-yaml': '4'
  '@types/koa-bodyparser': ^4.3.12
  '@types/koa-compose': ^3.2.8
  '@types/koa-range': ^0.3.5
  '@types/methods': ^1.1.4
  '@types/mime-types': ^3.0.0
  '@types/mocha': ^10.0.10
  '@types/mustache': ^4.2.5
  '@types/node': 24.5.2
  '@types/on-finished': ^2.3.4
  '@types/parseurl': ^1.3.3
  '@types/safe-timers': ^1.1.2
  '@types/stack-trace': ^0.0.33
  '@types/statuses': ^2.0.5
  '@types/superagent': ^8.1.9
  '@types/type-is': ^1.6.6
  '@types/vary': ^1.1.3
  '@vitest/coverage-v8': 4.0.0-beta.13
  '@vitest/ui': 4.0.0-beta.13
  accepts: ^1.3.8
  address: '2'
  assert-file: '1'
  await-event: '2'
  beautify-benchmark: ^0.2.4
  benchmark: ^2.1.4
  body-parser: ^2.0.0
  c8: 10.1.3
  cache-content-type: ^2.0.0
  camelcase: ^8.0.0
  cfork: ^2.0.0
  ci-parallel-vars: ^1.0.1
  circular-json-for-egg: ^1.0.0
  cluster-client: ^3.7.0
  cluster-reload: ^2.0.0
  coffee: '5'
  content-disposition: ~0.5.4
  content-type: ^1.0.5
  cookie: ^1.0.2
  cookie-parser: ^1.4.6
  cookies: ^0.9.1
  cpy: ^12.0.0
  cpy-cli: ^6.0.0
  cron-parser: ^4.9.0
  cross-env: ^10.0.0
  cross-spawn: ^7.0.6
  debounce: ^2.2.0
  destroy: ^1.0.4
  detect-port: ^2.1.0
  dumi: ^2.4.17
  egg-errors: ^2.3.2
  egg-logger: ^3.5.0
  egg-path-matching: ^2.0.0
  egg-plugin-puml: ^2.4.0
  egg-tracer: ^2.1.0
  egg-ts-helper: ^3.0.0
  egg-view-nunjucks: ^2.3.0
  encodeurl: ^2.0.0
  esbuild: ^0.25.0
  esbuild-register: ^3.6.0
  escape-html: ^1.0.3
  execa: ^9.6.0
  express: ^4.21.2
  formstream: ^1.5.1
  fresh: ~0.5.2
  fs-readdir-recursive: ^1.1.0
  gals: '1'
  get-ready: ^3.1.0
  globby: ^11.0.2
  graceful: ^2.0.0
  graceful-process: ^2.0.0
  http-errors: ^2.0.0
  humanize-ms: ^2.0.0
  husky: ^9.1.7
  is-type-of: ^2.2.0
  jest-changed-files: ^30.0.0
  jsonp-body: ^2.0.0
  js-yaml: ^4.1.0
  keygrip: ^1.0.2
  koa-bodyparser: ^4.4.1
  koa-compose: ^4.1.0
  koa-onerror: ^5.0.1
  koa-override: ^4.0.0
  koa-range: ^0.3.0
  koa-static: ^5.0.0
  lint-staged: ^16.2.0
  merge-descriptors: ^2.0.0
  mime-types: ^3.0.0
  mm: ^4.0.2
  mocha: 11.7.2
  mochawesome-with-mocha: 8.0.0
  mri: ^1.2.0
  multimatch: ^7.0.0
  mustache: ^4.2.0
  node-homedir: ^2.0.0
  npminstall: ^7.12.0
  on-finished: ^2.4.1
  onelogger: ^1.0.1
  oxlint: ^1.18.0
  oxlint-tsgolint: ^0.2.0
  parseurl: ^1.3.3
  pedding: ^2.0.1
  performance-ms: ^1.1.0
  picocolors: ^1.1.1
  prettier: ^3.6.2
  ready-callback: ^4.0.0
  rimraf: ^6.0.1
  runscript: ^2.0.1
  safe-timers: ^1.1.0
  sdk-base: ^5.0.1
  semver: ^7.7.2
  sendmessage: ^3.0.1
  should-send-same-site-none: ^2.0.5
  spy: ^1.0.0
  stack-trace: ^0.0.10
  statuses: ^2.0.1
  superagent: ^10.0.0
  terminal-link: ^5.0.0
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsd: ^0.33.0
  tsdown: ^0.15.4
  tshy: ^3.0.0
  tshy-after: ^1.0.0
  type-fest: ^5.0.1
  type-is: ^2.0.0
  typescript: 5.9.2
  urllib: ^4.8.2
  utility: ^2.5.0
  vary: ^1.1.2
  vitest: 4.0.0-beta.13
  ylru: ^2.0.0

catalogMode: prefer

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@eggjs/*'
  - '@vitest/*'
  - '@rolldown/*'
  - '@vitejs/*'
  - '@oxc-project/*'
  - rolldown
  - vitest
  - vite
  - rolldown-vite

overrides:
  less: ^4.4.1
  vite: npm:rolldown-vite@^7.1.13
