import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react", "node", "jsdoc"],
    categories: {
      correctness: "warn",
    },
    $schema: "./node_modules/oxlint/configuration_schema.json",
    env: {
      builtin: true,
      commonjs: true,
      es2024: true,
      mocha: true,
    },
    ignorePatterns: [
      "test/fixtures/**",
      "examples/**/app/public/**",
      "logs/**",
      "run/**",
      "docs/node_modules/**",
      "site/**",
    ],
    rules: {
      "array-callback-return": "error",
      "block-scoped-var": "error",
      curly: ["error", "multi-line"],
      "default-case": [
        "error",
        {
          commentPattern: "^no default$",
        },
      ],
      eqeqeq: ["error", "smart"],
      "no-alert": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-else-return": "error",
      "no-empty-function": [
        "error",
        {
          allow: ["arrowFunctions", "functions", "methods", "constructors"],
        },
      ],
      "no-empty-pattern": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-iterator": "off",
      "no-labels": [
        "error",
        {
          allowLoop: false,
          allowSwitch: false,
        },
      ],
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-multi-str": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-proto": "error",
      "no-redeclare": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-unused-expressions": "off",
      "no-unused-labels": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-with": "error",
      yoda: "error",
      "no-delete-var": "error",
      "no-label-var": "error",
      "no-shadow-restricted-names": "error",
      "no-undef": "error",
      "no-unused-vars": [
        "error",
        {
          vars: "local",
          args: "after-used",
        },
      ],
      "no-use-before-define": ["error", { functions: false, classes: true, variables: true }],
      "no-array-constructor": "error",
      "no-bitwise": "error",
      "no-unneeded-ternary": "error",
      "node/no-new-require": "error",
      "no-cond-assign": ["error", "except-parens"],
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-func-assign": "error",
      "no-inner-declarations": ["error", "functions"],
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-obj-calls": "error",
      "no-regex-spaces": "error",
      "no-sparse-arrays": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "use-isnan": "error",
      "valid-typeof": "off",
      "jsdoc/check-property-names": "off",
      "jsdoc/check-tag-names": "off",
      "jsdoc/no-defaults": "off",
      "jsdoc/require-param": "warn",
      "jsdoc/require-param-description": "off",
      "jsdoc/require-param-name": "warn",
      "jsdoc/require-param-type": "warn",
      "jsdoc/require-returns-description": "off",
      "jsdoc/require-returns-type": "warn",
      "@typescript-eslint/unbound-method": "off",
      "@typescript-eslint/no-redundant-type-constituents": "off",
      "@typescript-eslint/no-unsafe-declaration-merging": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/await-thenable": "off",
      "no-restricted-imports": [
        "error",
        "assert",
        "assert/strict",
        "async_hooks",
        "buffer",
        "child_process",
        "cluster",
        "console",
        "constants",
        "crypto",
        "dgram",
        "diagnostics_channel",
        "dns",
        "domain",
        "events",
        "fs",
        "fs/promises",
        "http",
        "http2",
        "https",
        "inspector",
        "module",
        "net",
        "os",
        "path",
        "perf_hooks",
        "process",
        "punycode",
        "querystring",
        "readline",
        "readline/promises",
        "repl",
        "stream",
        "stream/web",
        "string_decoder",
        "sys",
        "test",
        "timers",
        "timers/promises",
        "tls",
        "trace_events",
        "tty",
        "url",
        "util",
        "v8",
        "vm",
        "wasi",
        "worker_threads",
        "zlib",
      ],
      "constructor-super": "off",
      "no-class-assign": "error",
      "no-const-assign": "error",
      "no-dupe-class-members": "error",
      "no-this-before-super": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "prefer-const": [
        "error",
        {
          destructuring: "all",
          ignoreReadBeforeAssign: true,
        },
      ],
      "require-yield": "off",
      "prefer-promise-reject-errors": "error",
      "eggache/no-only-tests": "warn",
      "eggache/no-override-exports": "error",
      "eggache/no-unexpected-plugin-keys": "error",
    },
    globals: {
      __dirname: "readonly",
      __filename: "readonly",
      AbortController: "readonly",
      AbortSignal: "readonly",
      atob: "readonly",
      Blob: "readonly",
      BroadcastChannel: "readonly",
      btoa: "readonly",
      Buffer: "readonly",
      ByteLengthQueuingStrategy: "readonly",
      clearImmediate: "readonly",
      clearInterval: "readonly",
      clearTimeout: "readonly",
      CompressionStream: "readonly",
      console: "readonly",
      CountQueuingStrategy: "readonly",
      crypto: "readonly",
      Crypto: "readonly",
      CryptoKey: "readonly",
      CustomEvent: "readonly",
      DecompressionStream: "readonly",
      DOMException: "readonly",
      Event: "readonly",
      EventTarget: "readonly",
      File: "readonly",
      FormData: "readonly",
      Headers: "readonly",
      MessageChannel: "readonly",
      MessageEvent: "readonly",
      MessagePort: "readonly",
      PerformanceEntry: "readonly",
      PerformanceMark: "readonly",
      PerformanceMeasure: "readonly",
      PerformanceObserver: "readonly",
      PerformanceObserverEntryList: "readonly",
      PerformanceResourceTiming: "readonly",
      process: "readonly",
      queueMicrotask: "readonly",
      ReadableByteStreamController: "readonly",
      ReadableStream: "readonly",
      ReadableStreamBYOBReader: "readonly",
      ReadableStreamBYOBRequest: "readonly",
      ReadableStreamDefaultController: "readonly",
      ReadableStreamDefaultReader: "readonly",
      Request: "readonly",
      Response: "readonly",
      setImmediate: "readonly",
      setInterval: "readonly",
      setTimeout: "readonly",
      structuredClone: "readonly",
      SubtleCrypto: "readonly",
      TextDecoder: "readonly",
      TextDecoderStream: "readonly",
      TextEncoder: "readonly",
      TextEncoderStream: "readonly",
      TransformStream: "readonly",
      TransformStreamDefaultController: "readonly",
      URLSearchParams: "readonly",
      WebAssembly: "readonly",
      WritableStream: "readonly",
      WritableStreamDefaultController: "readonly",
      WritableStreamDefaultWriter: "readonly",
    },
    settings: {
      jsdoc: {
        tagNamePreference: {
          returns: "return",
        },
      },
    },
    jsPlugins: ["eslint-plugin-eggache"],
  },
});
