import fs from 'node:fs/promises';
import path from 'node:path';

import { PrototypeUtil } from '@eggjs/core-decorator';
import { ClassProtoDescriptor } from '@eggjs/metadata';
import type { EggProtoImplClass, ProtoDescriptor } from '@eggjs/tegg-types';

/**
 * Generates a temporary TypeScript entry file for bundling a single controller method.
 *
 * The entry file imports all required classes as side-effects (which triggers their
 * decorator registration in the DI container), then re-exports the controller class.
 *
 * When bundled with tree shaking, only the code reachable from this entry is included.
 */
export class EntryGenerator {
  /**
   * Generate an entry file for one controller method.
   *
   * @param outputDir - Directory where the entry file will be written
   * @param controllerClazz - The controller class
   * @param methodName - Name of the controller method being bundled
   * @param deps - All dependency proto descriptors (direct + transitive)
   * @returns Absolute path to the generated entry file
   */
  async generate(
    outputDir: string,
    controllerClazz: EggProtoImplClass,
    methodName: string,
    deps: ProtoDescriptor[],
  ): Promise<string> {
    const controllerFilePath = PrototypeUtil.getFilePath(controllerClazz);
    if (!controllerFilePath) {
      throw new Error(`Cannot find file path for controller class ${controllerClazz.name}`);
    }

    const lines: string[] = [
      `// AUTO-GENERATED: ${controllerClazz.name}.${methodName} entry`,
      `// DO NOT EDIT - this file is generated by @eggjs/tegg-bundler`,
      ``,
    ];

    // Import controller file as side effect (registers controller proto via decorators)
    lines.push(`import ${JSON.stringify(this.#toRelativeImport(outputDir, controllerFilePath))};`);

    // Import each dependency file as side effect (registers dep proto via decorators)
    const importedPaths = new Set<string>([controllerFilePath]);
    for (const dep of deps) {
      if (!ClassProtoDescriptor.isClassProtoDescriptor(dep)) continue;

      const depFilePath = PrototypeUtil.getFilePath(dep.clazz);
      if (!depFilePath || importedPaths.has(depFilePath)) continue;

      importedPaths.add(depFilePath);
      lines.push(`import ${JSON.stringify(this.#toRelativeImport(outputDir, depFilePath))};`);
    }

    lines.push(``);
    lines.push(
      `export { ${controllerClazz.name} } from ${JSON.stringify(this.#toRelativeImport(outputDir, controllerFilePath))};`,
    );
    lines.push(``);

    await fs.mkdir(outputDir, { recursive: true });
    const entryFileName = `${controllerClazz.name}.${methodName}.entry.ts`;
    const entryPath = path.join(outputDir, entryFileName);
    await fs.writeFile(entryPath, lines.join('\n'));

    return entryPath;
  }

  /**
   * Convert an absolute file path to a relative import specifier from the given directory.
   * Always produces a path starting with `./` or `../` for bundler compatibility.
   */
  #toRelativeImport(fromDir: string, toPath: string): string {
    const rel = path.relative(fromDir, toPath).replace(/\\/g, '/');
    return rel.startsWith('.') ? rel : `./${rel}`;
  }
}
