/**
 * Snapshot prelude generation.
 *
 * In snapshot mode the bundler prepends this prelude to the emitted single-file
 * `worker.js`, BEFORE the bundle IIFE (`((__UTOOPACK__)=>{...})([...modules])`),
 * so it runs before any bundled module is evaluated. PR3 fills the body with the
 * lazy-require / native-binding stub mechanism that converges non-serializable
 * native bindings for V8 startup snapshots. For now it is an intentional no-op
 * skeleton plus a placeholder hook so the wiring (generate → prepend → detect) is
 * in place and testable.
 */

/**
 * Marker comment embedded in the prelude. Used to detect an already-prepended
 * prelude so {@link prependSnapshotPrelude} stays idempotent across re-runs.
 */
export const SNAPSHOT_PRELUDE_MARKER = '@eggjs/egg-bundler:snapshot-prelude';

/**
 * Render the snapshot prelude source. The result is plain CommonJS (the bundle
 * output package.json is `{ "type": "commonjs" }`) and must be safe to execute at
 * the very top of the worker file, before the bundle IIFE.
 */
export function renderSnapshotPrelude(): string {
  return [
    `// ⚠️ auto-generated by @eggjs/egg-bundler — snapshot prelude (do not edit)`,
    `// marker: ${SNAPSHOT_PRELUDE_MARKER}`,
    `// Runs before the bundle IIFE so it executes before any bundled module loads.`,
    `// PR3 installs the lazy-require / native-binding stub mechanism here; this is`,
    `// currently an intentional no-op placeholder.`,
    `(function eggBundlerSnapshotPrelude() {`,
    `  // PR3: install lazy-require / native-binding stubs before module evaluation.`,
    `})();`,
    ``,
  ].join('\n');
}

/**
 * Prepend the snapshot prelude to `source`, preserving a leading shebang and a
 * leading `"use strict"` / `'use strict'` directive so neither is demoted out of
 * the directive prologue. Idempotent: if the prelude marker is already present the
 * source is returned unchanged.
 */
export function prependSnapshotPrelude(source: string): string {
  // Only look for the marker in the file head (the prelude is short and always
  // sits at the very top). A whole-file `includes` would false-positive if any
  // bundled application/dependency code happened to contain the marker string,
  // silently skipping prelude injection.
  if (source.slice(0, 1024).includes(SNAPSHOT_PRELUDE_MARKER)) {
    return source;
  }

  const prelude = renderSnapshotPrelude();
  const lines = source.split('\n');
  let insertAt = 0;

  // Keep a shebang on the very first line.
  if (lines[0]?.startsWith('#!')) {
    insertAt = 1;
  }
  // Keep a leading "use strict" directive ahead of the prelude.
  const directive = lines[insertAt]?.trim();
  if (directive === '"use strict";' || directive === "'use strict';") {
    insertAt += 1;
  }

  if (insertAt === 0) {
    return prelude + source;
  }
  const head = lines.slice(0, insertAt).join('\n');
  const tail = lines.slice(insertAt).join('\n');
  return `${head}\n${prelude}${tail}`;
}
