name: 💡 Feature Request For Eggjs
description: I have a suggestion (and may want to implement it)!
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        You have an idea how to improve the Eggjs?

        Before submitting, please have a look at the existing issues if there's already
        something related to your suggestion.
  - type: textarea
    attributes:
      label: "Enter your suggestions in details:"
      placeholder: |
        1. What I expected to happen?

        2. Your reason (e.g: I'm always frustrated with...).
        If possible, images or videos are welcome.

        3. What I plan to do (Optional but better in pseudo codes).
    validations:
      required: true
