<div class="footer">
  <footer>
    <ul>
    <li>Latest: <strong>0.10.0</strong></li>
    <li>Node.js >= <strong> 6.0.0</strong></li>
    </ul>

    <div class="license">Released under the MIT License <a href="https://github.com/eggjs"><img src="/images/github.svg"/></a></div>
  </footer>
</div>
<div class="cnzz">
<script src="https://s11.cnzz.com/z_stat.php?id=1261142226&web_id=1261142226" language="JavaScript"></script>
</div>
