title: Egg.js
subtitle: "Born to build better enterprise frameworks and apps"
description: "Born to build better enterprise frameworks and apps"
language:
- en
- zh-cn
timezone: UTC
url: https://eggjs.org
root: /
archive_dir: news
permalink: news/:year/:month/:day/:title/
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: egg

less:
  compress: true

deer:
  spmAPos: 'a454'
  spmBPos: 'b4893'
