@startuml
digraph plugins {
  onerror
  session
  i18n
  watcher
  multipart
  security
  development
  logrotator
  schedule
  static
  jsonp
  view
  security -> session
  development -> watcher
  logrotator -> schedule
  jsonp -> security [style=dotted]
}
@enduml
