
@startuml
digraph world {
  "onerror";
  "session";
  "i18n";
  "watcher";
  "multipart";
  "security" -> "session";
  "development" -> "watcher";
  "logrotator" -> "schedule";
  "schedule";
  "static";
  "jsonp" -> "security";
  "view";
}
@enduml
