name: CI cluster2

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      os: 'ubuntu-latest, windows-latest'
      version: '22'
      test: 'npm run ci:cluster2'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
